server:
  port: 8099
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8763/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: track-service

  data:
    mongodb:
      repositories:
        enabled: true

    host: localhost

driverClassName: mongodb.jdbc.MongoDrive


logging:
  level:
    com.stackroute.route: DEBUG